/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.cm.fetchset.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2010-03-30 11:47:51
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class FetchSetItemVO extends SuperVO {

	private java.lang.String pk_workitem;
	private java.lang.String pk_costobject;
	private java.lang.String pk_qcdept;
	private java.lang.String pk_serverdept;
	private java.lang.String pk_largeritem;
	private java.lang.String pk_factor;
	private java.lang.String pk_factorgroup;

	private java.lang.String cfetchsetid;

	private java.lang.String pk_group;

	private java.lang.String pk_org;

	private java.lang.String pk_org_v;

	private java.lang.String cfetchset_bid;

	private java.lang.String pk_billtypecode;

	private java.lang.Integer dr = 0;

	private nc.vo.pub.lang.UFDateTime ts;

	private String pk_costcenter;

	// add by wtf at 2011-04 单据类型id，原来的pk_billtypecode用于保存单据的编码
	private String pk_billtypeid;

	public static final String PK_COSTCENTER = "pk_costcenter";

	public static final String PK_BILLTYPEID = "pk_billtypeid";

	public static final String CFETCHSETID = "cfetchsetid";

	public static final String PK_GROUP = "pk_group";

	public static final String PK_ORG = "pk_org";

	public static final String PK_ORG_V = "pk_org_v";

	public static final String CFETCHSET_BID = "cfetchset_bid";

	public static final String PK_BILLTYPECODE = "pk_billtypecode";

	public static final String META_DATA = "cm.cm_fetchset_b";

	@Override
	public IVOMeta getMetaData() {
		// TODO Auto-generated method stub
		return VOMetaFactory.getInstance().getVOMeta(FetchSetItemVO.META_DATA);
	}

	/**
	 * 属性cfetchsetid的Getter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCfetchsetid() {
		return this.cfetchsetid;
	}

	/**
	 * 属性cfetchsetid的Setter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @param newCfetchsetid
	 *            java.lang.String
	 */
	public void setCfetchsetid(java.lang.String newCfetchsetid) {
		this.cfetchsetid = newCfetchsetid;
	}

	/**
	 * 属性pk_group的Getter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group() {
		return this.pk_group;
	}

	/**
	 * 属性pk_group的Setter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @param newPk_group
	 *            java.lang.String
	 */
	public void setPk_group(java.lang.String newPk_group) {
		this.pk_group = newPk_group;
	}

	/**
	 * 属性pk_org的Getter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org() {
		return this.pk_org;
	}

	/**
	 * 属性pk_org的Setter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @param newPk_org
	 *            java.lang.String
	 */
	public void setPk_org(java.lang.String newPk_org) {
		this.pk_org = newPk_org;
	}

	/**
	 * 属性pk_org_v的Getter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org_v() {
		return this.pk_org_v;
	}

	/**
	 * 属性pk_org_v的Setter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @param newPk_org_v
	 *            java.lang.String
	 */
	public void setPk_org_v(java.lang.String newPk_org_v) {
		this.pk_org_v = newPk_org_v;
	}

	/**
	 * 属性cfetchset_bid的Getter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCfetchset_bid() {
		return this.cfetchset_bid;
	}

	/**
	 * 属性cfetchset_bid的Setter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @param newCfetchset_bid
	 *            java.lang.String
	 */
	public void setCfetchset_bid(java.lang.String newCfetchset_bid) {
		this.cfetchset_bid = newCfetchset_bid;
	}

	/**
	 * 属性pk_billtypecode的Getter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_billtypecode() {
		return this.pk_billtypecode;
	}

	/**
	 * 属性pk_billtypecode的Setter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @param newPk_billtypecode
	 *            java.lang.String
	 */
	public void setPk_billtypecode(java.lang.String newPk_billtypecode) {
		this.pk_billtypecode = newPk_billtypecode;
	}

	/**
	 * 属性dr的Getter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr() {
		return this.dr;
	}

	/**
	 * 属性dr的Setter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @param newDr
	 *            java.lang.Integer
	 */
	public void setDr(java.lang.Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * 属性ts的Getter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs() {
		return this.ts;
	}

	/**
	 * 属性ts的Setter方法. 创建日期:2010-03-30 11:47:51
	 * 
	 * @param newTs
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2010-03-30 11:47:51
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getParentPKFieldName() {
		return "cfetchsetid";
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2010-03-30 11:47:51
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getPKFieldName() {
		return "cfetchset_bid";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2010-03-30 11:47:51
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getTableName() {
		return "cm_fetchset_b";
	}

	public static java.lang.String getDefaultTableName() {
		return "cm_fetchset_b";
	}

	/**
	 * 按照默认方式创建构造子. 创建日期:2010-03-30 11:47:51
	 */
	public FetchSetItemVO() {
		super();
	}

	public String getPk_billtypeid() {
		return this.pk_billtypeid;
	}

	public void setPk_billtypeid(String pk_billtypeid) {
		this.pk_billtypeid = pk_billtypeid;
	}

	/**
	 * 获得 pk_costcenter 的属性值
	 * 
	 * @return the pk_costcenter
	 * @since 2015-1-20
	 * @author zhangweix
	 */
	public String getPk_costcenter() {
		return this.pk_costcenter;
	}

	/**
	 * 设置 pk_costcenter 的属性值
	 * 
	 * @param pk_costcenter
	 *            the pk_costcenter to set
	 * @since 2015-1-20
	 * @author zhangweix
	 */
	public void setPk_costcenter(String pk_costcenter) {
		this.pk_costcenter = pk_costcenter;
	}

	public java.lang.String getPk_workitem() {
		return pk_workitem;
	}

	public void setPk_workitem(java.lang.String pk_workitem) {
		this.pk_workitem = pk_workitem;
	}

	public java.lang.String getPk_costobject() {
		return pk_costobject;
	}

	public void setPk_costobject(java.lang.String pk_costobject) {
		this.pk_costobject = pk_costobject;
	}

	public java.lang.String getPk_qcdept() {
		return pk_qcdept;
	}

	public void setPk_qcdept(java.lang.String pk_qcdept) {
		this.pk_qcdept = pk_qcdept;
	}

	public java.lang.String getPk_serverdept() {
		return pk_serverdept;
	}

	public void setPk_serverdept(java.lang.String pk_serverdept) {
		this.pk_serverdept = pk_serverdept;
	}

	public java.lang.String getPk_largeritem() {
		return pk_largeritem;
	}

	public void setPk_largeritem(java.lang.String pk_largeritem) {
		this.pk_largeritem = pk_largeritem;
	}

	public java.lang.String getPk_factor() {
		return pk_factor;
	}

	public void setPk_factor(java.lang.String pk_factor) {
		this.pk_factor = pk_factor;
	}

	public java.lang.String getPk_factorgroup() {
		return pk_factorgroup;
	}

	public void setPk_factorgroup(java.lang.String pk_factorgroup) {
		this.pk_factorgroup = pk_factorgroup;
	}

}
