
  CREATE TABLE IC_FIVEMETALS_H 
   (	PK_GROUP VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	PK_ORG VARCHAR2(20 BYTE) DEFAULT '~', 
	PK_ORG_V VARCHAR2(20 BYTE) DEFAULT '~', 
	PK_FIVEMETALS_H CHAR(20 BYTE) NOT NULL ENABLE, 
	CODE VARCHAR2(50 BYTE), 
	NAME VARCHAR2(50 BYTE), 
	VCARDNO VARCHAR2(50 BYTE), 
	VPROJECT VARCHAR2(50 BYTE), 
	VDEPARTMENT VARCHAR2(50 BYTE), 
	VREMARK VARCHAR2(50 BYTE), 
	VCARDTYPE NUMBER(*,0), 
	DEF1 VARCHAR2(100 BYTE), 
	DEF2 VARCHAR2(100 BYTE), 
	DEF3 VARCHAR2(100 BYTE), 
	DEF4 NUMBER(28,8), 
	DEF5 NUMBER(28,8), 
	DEF6 NUMBER(28,8), 
	DEF7 CHAR(1 BYTE), 
	DEF8 CHAR(1 BYTE), 
	DEF9 CHAR(19 BYTE), 
	DEF10 CHAR(19 BYTE), 
	DBILLDATE CHAR(19 BYTE), 
	PK_BILLTYPE VARCHAR2(50 BYTE), 
	CREATOR VARCHAR2(20 BYTE) DEFAULT '~', 
	CREATIONTIME CHAR(19 BYTE), 
	MODIFIER VARCHAR2(20 BYTE) DEFAULT '~', 
	MODIFIEDTIME CHAR(19 BYTE), 
	VBILLSTATUS NUMBER(*,0), 
	TS CHAR(19 BYTE), 
	DR NUMBER(*,0) DEFAULT 0, 
	 CONSTRAINT PK_IC_FIVEMETALS_H PRIMARY KEY (PK_FIVEMETALS_H)
 
   );


  CREATE TABLE IC_FIVEMETALS_B 
   (	ROWNO VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	NMNY NUMBER(28,8), 
	ITYPE NUMBER(*,0), 
	VREMARK VARCHAR2(50 BYTE), 
	VSOURCETYPE VARCHAR2(50 BYTE), 
	VSOURCEBILLID VARCHAR2(50 BYTE), 
	VSOURCEBILLNO VARCHAR2(50 BYTE), 
	DEF1 VARCHAR2(100 BYTE), 
	DEF2 VARCHAR2(100 BYTE), 
	DEF3 VARCHAR2(100 BYTE), 
	DEF4 NUMBER(28,8), 
	DEF5 NUMBER(28,8), 
	DEF6 NUMBER(28,8), 
	DEF7 CHAR(1 BYTE), 
	DEF8 CHAR(1 BYTE), 
	DEF9 CHAR(19 BYTE), 
	DEF10 CHAR(19 BYTE), 
	PK_FIVEMETALS_B CHAR(20 BYTE) NOT NULL ENABLE, 
	MAKETIME CHAR(19 BYTE) NOT NULL ENABLE, 
	LASTMAKETIME CHAR(19 BYTE), 
	CREATOR VARCHAR2(20 BYTE) DEFAULT '~', 
	CPERIOD VARCHAR2(50 BYTE), 
	PK_FIVEMETALS_H CHAR(20 BYTE) NOT NULL ENABLE, 
	TS CHAR(19 BYTE), 
	DR NUMBER(*,0) DEFAULT 0, 
	 CONSTRAINT PK_IC_FIVEMETALS_B PRIMARY KEY (PK_FIVEMETALS_B)
   ) ;
 

 
