create table ic_fivemetals_h (
pk_group varchar(20) NOT NULL,
pk_org varchar(20) default '~' NULL,
pk_org_v varchar(20) default '~' NULL,
pk_fivemetals_h char(20) NOT NULL,
code varchar(50) NULL,
name varchar(50) NULL,
vcardno varchar(50) NULL,
vproject varchar(50) NULL,
vdepartment varchar(50) NULL,
vremark varchar(50) NULL,
vcardtype int NULL,
def1 varchar(100) NULL,
def2 varchar(100) NULL,
def3 varchar(100) NULL,
def4 decimal(28,8) NULL,
def5 decimal(28,8) NULL,
def6 decimal(28,8) NULL,
def7 char(1) NULL,
def8 char(1) NULL,
def9 char(19) NULL,
def10 char(19) NULL,
dbilldate char(19) NULL,
pk_billtype varchar(50) NULL,
creator varchar(20) default '~' NULL,
creationtime char(19) NULL,
modifier varchar(20) default '~' NULL,
modifiedtime char(19) NULL,
vbillstatus int NULL,
CONSTRAINT PK_IC_FIVEMETALS_H PRIMARY KEY (pk_fivemetals_h),
ts char(19) NULL,
dr smallint default 0 
)


create table ic_fivemetals_b (
rowno varchar(50) NOT NULL,
nmny decimal(28,8) NULL,
itype int NULL,
vremark varchar(50) NULL,
vsourcetype varchar(50) NULL,
vsourcebillid varchar(50) NULL,
vsourcebillno varchar(50) NULL,
def1 varchar(100) NULL,
def2 varchar(100) NULL,
def3 varchar(100) NULL,
def4 decimal(28,8) NULL,
def5 decimal(28,8) NULL,
def6 decimal(28,8) NULL,
def7 char(1) NULL,
def8 char(1) NULL,
def9 char(19) NULL,
def10 char(19) NULL,
pk_fivemetals_b char(20) NOT NULL,
maketime char(19) NOT NULL,
lastmaketime char(19) NULL,
creator varchar(20) default '~' NULL,
cperiod varchar(50) NULL,
pk_fivemetals_h char(20) NOT NULL,
CONSTRAINT PK_IC_FIVEMETALS_B PRIMARY KEY (pk_fivemetals_b),
ts char(19) NULL,
dr smallint default 0 
)


