/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.bd.bom.bom0202.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class BomVO extends SuperVO {

	public static final String VFREE1 = "vfree1";

	public static final String VFREE2 = "vfree2";

	public static final String VFREE3 = "vfree3";

	public static final String VFREE4 = "vfree4";

	public static final String VFREE5 = "vfree5";

	public static final String VFREE6 = "vfree6";

	public static final String VFREE7 = "vfree7";

	public static final String VFREE8 = "vfree8";

	public static final String VFREE9 = "vfree9";

	public static final String VFREE10 = "vfree10";

	public static final String CBOMID = "cbomid";

	public static final String PK_GROUP = "pk_group";

	public static final String PK_ORG = "pk_org";

	public static final String PK_ORG_V = "pk_org_v";

	public static final String HCMATERIALID = "hcmaterialid";

	public static final String HVPLAINTEXT = "hvplaintext";

	public static final String HCMATERIALVID = "hcmaterialvid";

	public static final String HBISFEATURE = "hbisfeature";

	public static final String HCFEATURECLASSID = "hcfeatureclassid";

	public static final String HCFEATURECODE = "hcfeaturecode";

	public static final String HCMEASUREID = "hcmeasureid";

	public static final String HCASSMEASUREID = "hcassmeasureid";

	public static final String FBOMTYPE = "fbomtype";

	public static final String HVERSION = "hversion";

	public static final String HFVERSIONTYPE = "hfversiontype";

	public static final String HNASSPARENTNUM = "hnassparentnum";

	public static final String HNPARENTNUM = "hnparentnum";

	public static final String HBDEFAULT = "hbdefault";

	public static final String CREATOR = "creator";

	public static final String CREATIONTIME = "creationtime";

	public static final String MODIFIER = "modifier";

	public static final String MODIFIEDTIME = "modifiedtime";

	public static final String APPROVER = "approver";

	public static final String TAUDITTIME = "taudittime";

	public static final String BILLMAKER = "billmaker";

	public static final String TMAKETIME = "tmaketime";

	public static final String FBILLSTATUS = "fbillstatus";

	public static final String HVNOTE = "hvnote";

	public static final String HCPROJECTID = "hcprojectid";

	public static final String HVCHANGERATE = "hvchangerate";

	public static final String HVDEF1 = "hvdef1";

	public static final String HVDEF2 = "hvdef2";

	public static final String HVDEF3 = "hvdef3";

	public static final String HVDEF4 = "hvdef4";

	public static final String HVDEF5 = "hvdef5";

	public static final String HVDEF6 = "hvdef6";

	public static final String HVDEF7 = "hvdef7";

	public static final String HVDEF8 = "hvdef8";

	public static final String HVDEF9 = "hvdef9";

	public static final String HVDEF10 = "hvdef10";

	public static final String HVDEF11 = "hvdef11";

	public static final String HVDEF12 = "hvdef12";

	public static final String HVDEF13 = "hvdef13";

	public static final String HVDEF14 = "hvdef14";

	public static final String HVDEF15 = "hvdef15";

	public static final String HVDEF16 = "hvdef16";

	public static final String HVDEF17 = "hvdef17";

	public static final String HVDEF18 = "hvdef18";

	public static final String HVDEF19 = "hvdef19";

	public static final String HVDEF20 = "hvdef20";

	public static final String HFBOMSOURCE = "hfbomsource";

	public static final String HCECNID = "hcecnid";

	public static final String HVECNBILLCODE = "hvecnbillcode";

	public static final String HRTVERSION = "hrtversion";

	public static final String HISWHOLESETSEND = "hiswholesetsend";

	public static final String HISVIRTUAL = "hisvirtual";

	public static final String BKITITEM = "bkititem";

	public static final String HMATERIALVID = "hmaterialvid";

	public static final String HCMATERIALNAME = "hcmaterialname";

	public static final String HLEVELNO = "hlevelno";

	public static final String HFMATERIALID = "hfmaterialid";

	public static final String HFBOMTYPE = "hfbomtype";

	public static final String HFBOMVERSION = "hfbomversion";

	public static final String HSRCID = "hsrcid";

	public static final String VBILLCODE = "vbillcode";

	public static final String VBILLTYPE = "vbilltype";

	public static final String HBCUSTOMIZED = "hbcustomized";

	public static final String TABLE_NAME = "bd_bom";

	public static final String HFBILLSTATUS = "hfbillstatus";
	
	
	  /**
     * 属性vfree1的Getter方法.属性名：自由辅助属性1
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree1() {
        return (java.lang.String) this.getAttributeValue("vfree1");
    }

    /**
     * 属性vfree1的Setter方法.属性名：自由辅助属性1
     * 创建日期:
     * 
     * @param newVfree1 java.lang.String
     */
    public void setVfree1(java.lang.String newVfree1) {
        this.setAttributeValue("vfree1", newVfree1);
    }

    /**
     * 属性vfree2的Getter方法.属性名：自由辅助属性2
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree2() {
        return (java.lang.String) this.getAttributeValue("vfree2");
    }

    /**
     * 属性vfree2的Setter方法.属性名：自由辅助属性2
     * 创建日期:
     * 
     * @param newVfree2 java.lang.String
     */
    public void setVfree2(java.lang.String newVfree2) {
        this.setAttributeValue("vfree2", newVfree2);
    }

    /**
     * 属性vfree3的Getter方法.属性名：自由辅助属性3
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree3() {
        return (java.lang.String) this.getAttributeValue("vfree3");
    }

    /**
     * 属性vfree3的Setter方法.属性名：自由辅助属性3
     * 创建日期:
     * 
     * @param newVfree3 java.lang.String
     */
    public void setVfree3(java.lang.String newVfree3) {
        this.setAttributeValue("vfree3", newVfree3);
    }

    /**
     * 属性vfree4的Getter方法.属性名：自由辅助属性4
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree4() {
        return (java.lang.String) this.getAttributeValue("vfree4");
    }

    /**
     * 属性vfree4的Setter方法.属性名：自由辅助属性4
     * 创建日期:
     * 
     * @param newVfree4 java.lang.String
     */
    public void setVfree4(java.lang.String newVfree4) {
        this.setAttributeValue("vfree4", newVfree4);
    }

    /**
     * 属性vfree5的Getter方法.属性名：自由辅助属性5
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree5() {
        return (java.lang.String) this.getAttributeValue("vfree5");
    }

    /**
     * 属性vfree5的Setter方法.属性名：自由辅助属性5
     * 创建日期:
     * 
     * @param newVfree5 java.lang.String
     */
    public void setVfree5(java.lang.String newVfree5) {
        this.setAttributeValue("vfree5", newVfree5);
    }

    /**
     * 属性vfree6的Getter方法.属性名：自由辅助属性6
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree6() {
        return (java.lang.String) this.getAttributeValue("vfree6");
    }

    /**
     * 属性vfree6的Setter方法.属性名：自由辅助属性6
     * 创建日期:
     * 
     * @param newVfree6 java.lang.String
     */
    public void setVfree6(java.lang.String newVfree6) {
        this.setAttributeValue("vfree6", newVfree6);
    }

    /**
     * 属性vfree7的Getter方法.属性名：自由辅助属性7
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree7() {
        return (java.lang.String) this.getAttributeValue("vfree7");
    }

    /**
     * 属性vfree7的Setter方法.属性名：自由辅助属性7
     * 创建日期:
     * 
     * @param newVfree7 java.lang.String
     */
    public void setVfree7(java.lang.String newVfree7) {
        this.setAttributeValue("vfree7", newVfree7);
    }

    /**
     * 属性vfree8的Getter方法.属性名：自由辅助属性8
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree8() {
        return (java.lang.String) this.getAttributeValue("vfree8");
    }

    /**
     * 属性vfree8的Setter方法.属性名：自由辅助属性8
     * 创建日期:
     * 
     * @param newVfree8 java.lang.String
     */
    public void setVfree8(java.lang.String newVfree8) {
        this.setAttributeValue("vfree8", newVfree8);
    }

    /**
     * 属性vfree9的Getter方法.属性名：自由辅助属性9
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree9() {
        return (java.lang.String) this.getAttributeValue("vfree9");
    }

    /**
     * 属性vfree9的Setter方法.属性名：自由辅助属性9
     * 创建日期:
     * 
     * @param newVfree9 java.lang.String
     */
    public void setVfree9(java.lang.String newVfree9) {
        this.setAttributeValue("vfree9", newVfree9);
    }

    /**
     * 属性vfree10的Getter方法.属性名：自由辅助属性10
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree10() {
        return (java.lang.String) this.getAttributeValue("vfree10");
    }

    /**
     * 属性vfree10的Setter方法.属性名：自由辅助属性10
     * 创建日期:
     * 
     * @param newVfree10 java.lang.String
     */
    public void setVfree10(java.lang.String newVfree10) {
        this.setAttributeValue("vfree10", newVfree10);
    }

	/**
	 * 属性cbomid的Getter方法.属性名：物料清单 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCbomid() {
		return (java.lang.String) this.getAttributeValue("cbomid");
	}

	/**
	 * 属性cbomid的Setter方法.属性名：物料清单 创建日期:
	 * 
	 * @param newCbomid
	 *            java.lang.String
	 */
	public void setCbomid(java.lang.String newCbomid) {
		this.setAttributeValue("cbomid", newCbomid);
	}

	/**
	 * 属性pk_group的Getter方法.属性名：集团 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group() {
		return (java.lang.String) this.getAttributeValue("pk_group");
	}

	/**
	 * 属性pk_group的Setter方法.属性名：集团 创建日期:
	 * 
	 * @param newPk_group
	 *            java.lang.String
	 */
	public void setPk_group(java.lang.String newPk_group) {
		this.setAttributeValue("pk_group", newPk_group);
	}

	/**
	 * 属性pk_org的Getter方法.属性名：计划组织最新版本 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org() {
		return (java.lang.String) this.getAttributeValue("pk_org");
	}

	/**
	 * 属性pk_org的Setter方法.属性名：计划组织最新版本 创建日期:
	 * 
	 * @param newPk_org
	 *            java.lang.String
	 */
	public void setPk_org(java.lang.String newPk_org) {
		this.setAttributeValue("pk_org", newPk_org);
	}

	/**
	 * 属性pk_org_v的Getter方法.属性名：计划组织 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org_v() {
		return (java.lang.String) this.getAttributeValue("pk_org_v");
	}

	/**
	 * 属性pk_org_v的Setter方法.属性名：计划组织 创建日期:
	 * 
	 * @param newPk_org_v
	 *            java.lang.String
	 */
	public void setPk_org_v(java.lang.String newPk_org_v) {
		this.setAttributeValue("pk_org_v", newPk_org_v);
	}

	/**
	 * 属性hcmaterialid的Getter方法.属性名：物料 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHcmaterialid() {
		return (java.lang.String) this.getAttributeValue("hcmaterialid");
	}

	/**
	 * 属性hcmaterialid的Setter方法.属性名：物料 创建日期:
	 * 
	 * @param newHcmaterialid
	 *            java.lang.String
	 */
	public void setHcmaterialid(java.lang.String newHcmaterialid) {
		this.setAttributeValue("hcmaterialid", newHcmaterialid);
	}

	/**
	 * 属性hvplaintext的Getter方法.属性名：物料真名 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvplaintext() {
		return (java.lang.String) this.getAttributeValue("hvplaintext");
	}

	/**
	 * 属性hvplaintext的Setter方法.属性名：物料真名 创建日期:
	 * 
	 * @param newHvplaintext
	 *            java.lang.String
	 */
	public void setHvplaintext(java.lang.String newHvplaintext) {
		this.setAttributeValue("hvplaintext", newHvplaintext);
	}

	/**
	 * 属性hcmaterialvid的Getter方法.属性名：物料版本 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHcmaterialvid() {
		return (java.lang.String) this.getAttributeValue("hcmaterialvid");
	}

	/**
	 * 属性hcmaterialvid的Setter方法.属性名：物料版本 创建日期:
	 * 
	 * @param newHcmaterialvid
	 *            java.lang.String
	 */
	public void setHcmaterialvid(java.lang.String newHcmaterialvid) {
		this.setAttributeValue("hcmaterialvid", newHcmaterialvid);
	}

	/**
	 * 属性hbisfeature的Getter方法.属性名：特征件 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getHbisfeature() {
		return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("hbisfeature");
	}

	/**
	 * 属性hbisfeature的Setter方法.属性名：特征件 创建日期:
	 * 
	 * @param newHbisfeature
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setHbisfeature(nc.vo.pub.lang.UFBoolean newHbisfeature) {
		this.setAttributeValue("hbisfeature", newHbisfeature);
	}

	/**
	 * 属性hcfeatureclassid的Getter方法.属性名：特征类 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHcfeatureclassid() {
		return (java.lang.String) this.getAttributeValue("hcfeatureclassid");
	}

	/**
	 * 属性hcfeatureclassid的Setter方法.属性名：特征类 创建日期:
	 * 
	 * @param newHcfeatureclassid
	 *            java.lang.String
	 */
	public void setHcfeatureclassid(java.lang.String newHcfeatureclassid) {
		this.setAttributeValue("hcfeatureclassid", newHcfeatureclassid);
	}

	/**
	 * 属性hcfeaturecode的Getter方法.属性名：特征码 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHcfeaturecode() {
		return (java.lang.String) this.getAttributeValue("hcfeaturecode");
	}

	/**
	 * 属性hcfeaturecode的Setter方法.属性名：特征码 创建日期:
	 * 
	 * @param newHcfeaturecode
	 *            java.lang.String
	 */
	public void setHcfeaturecode(java.lang.String newHcfeaturecode) {
		this.setAttributeValue("hcfeaturecode", newHcfeaturecode);
	}

	/**
	 * 属性hcmeasureid的Getter方法.属性名：主单位 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHcmeasureid() {
		return (java.lang.String) this.getAttributeValue("hcmeasureid");
	}

	/**
	 * 属性hcmeasureid的Setter方法.属性名：主单位 创建日期:
	 * 
	 * @param newHcmeasureid
	 *            java.lang.String
	 */
	public void setHcmeasureid(java.lang.String newHcmeasureid) {
		this.setAttributeValue("hcmeasureid", newHcmeasureid);
	}

	/**
	 * 属性hcassmeasureid的Getter方法.属性名：单位 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHcassmeasureid() {
		return (java.lang.String) this.getAttributeValue("hcassmeasureid");
	}

	/**
	 * 属性hcassmeasureid的Setter方法.属性名：单位 创建日期:
	 * 
	 * @param newHcassmeasureid
	 *            java.lang.String
	 */
	public void setHcassmeasureid(java.lang.String newHcassmeasureid) {
		this.setAttributeValue("hcassmeasureid", newHcassmeasureid);
	}

	/**
	 * 属性fbomtype的Getter方法.属性名：BOM类型 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getFbomtype() {
		return (java.lang.Integer) this.getAttributeValue("fbomtype");
	}

	/**
	 * 属性fbomtype的Setter方法.属性名：BOM类型 创建日期:
	 * 
	 * @param newFbomtype
	 *            java.lang.Integer
	 */
	public void setFbomtype(java.lang.Integer newFbomtype) {
		this.setAttributeValue("fbomtype", newFbomtype);
	}

	/**
	 * 属性hversion的Getter方法.属性名：BOM版本号 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHversion() {
		return (java.lang.String) this.getAttributeValue("hversion");
	}

	/**
	 * 属性hversion的Setter方法.属性名：BOM版本号 创建日期:
	 * 
	 * @param newHversion
	 *            java.lang.String
	 */
	public void setHversion(java.lang.String newHversion) {
		this.setAttributeValue("hversion", newHversion);
	}

	/**
	 * 属性hfversiontype的Getter方法.属性名：版本类型 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getHfversiontype() {
		return (java.lang.Integer) this.getAttributeValue("hfversiontype");
	}

	/**
	 * 属性hfversiontype的Setter方法.属性名：版本类型 创建日期:
	 * 
	 * @param newHfversiontype
	 *            java.lang.Integer
	 */
	public void setHfversiontype(java.lang.Integer newHfversiontype) {
		this.setAttributeValue("hfversiontype", newHfversiontype);
	}

	/**
	 * 属性hnassparentnum的Getter方法.属性名：父项数量 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getHnassparentnum() {
		return (nc.vo.pub.lang.UFDouble) this
				.getAttributeValue("hnassparentnum");
	}

	/**
	 * 属性hnassparentnum的Setter方法.属性名：父项数量 创建日期:
	 * 
	 * @param newHnassparentnum
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setHnassparentnum(nc.vo.pub.lang.UFDouble newHnassparentnum) {
		this.setAttributeValue("hnassparentnum", newHnassparentnum);
	}

	/**
	 * 属性hnparentnum的Getter方法.属性名：父项主数量 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getHnparentnum() {
		return (nc.vo.pub.lang.UFDouble) this.getAttributeValue("hnparentnum");
	}

	/**
	 * 属性hnparentnum的Setter方法.属性名：父项主数量 创建日期:
	 * 
	 * @param newHnparentnum
	 *            nc.vo.pub.lang.UFDouble
	 */
	public void setHnparentnum(nc.vo.pub.lang.UFDouble newHnparentnum) {
		this.setAttributeValue("hnparentnum", newHnparentnum);
	}

	/**
	 * 属性hbdefault的Getter方法.属性名：默认 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getHbdefault() {
		return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("hbdefault");
	}

	/**
	 * 属性hbdefault的Setter方法.属性名：默认 创建日期:
	 * 
	 * @param newHbdefault
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setHbdefault(nc.vo.pub.lang.UFBoolean newHbdefault) {
		this.setAttributeValue("hbdefault", newHbdefault);
	}

	/**
	 * 属性creator的Getter方法.属性名：创建人 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCreator() {
		return (java.lang.String) this.getAttributeValue("creator");
	}

	/**
	 * 属性creator的Setter方法.属性名：创建人 创建日期:
	 * 
	 * @param newCreator
	 *            java.lang.String
	 */
	public void setCreator(java.lang.String newCreator) {
		this.setAttributeValue("creator", newCreator);
	}

	/**
	 * 属性creationtime的Getter方法.属性名：创建时间 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime() {
		return (nc.vo.pub.lang.UFDateTime) this
				.getAttributeValue("creationtime");
	}

	/**
	 * 属性creationtime的Setter方法.属性名：创建时间 创建日期:
	 * 
	 * @param newCreationtime
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime(nc.vo.pub.lang.UFDateTime newCreationtime) {
		this.setAttributeValue("creationtime", newCreationtime);
	}

	/**
	 * 属性modifier的Getter方法.属性名：最后修改人 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getModifier() {
		return (java.lang.String) this.getAttributeValue("modifier");
	}

	/**
	 * 属性modifier的Setter方法.属性名：最后修改人 创建日期:
	 * 
	 * @param newModifier
	 *            java.lang.String
	 */
	public void setModifier(java.lang.String newModifier) {
		this.setAttributeValue("modifier", newModifier);
	}

	/**
	 * 属性modifiedtime的Getter方法.属性名：最后修改时间 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime() {
		return (nc.vo.pub.lang.UFDateTime) this
				.getAttributeValue("modifiedtime");
	}

	/**
	 * 属性modifiedtime的Setter方法.属性名：最后修改时间 创建日期:
	 * 
	 * @param newModifiedtime
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime(nc.vo.pub.lang.UFDateTime newModifiedtime) {
		this.setAttributeValue("modifiedtime", newModifiedtime);
	}

	/**
	 * 属性approver的Getter方法.属性名：审批人 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getApprover() {
		return (java.lang.String) this.getAttributeValue("approver");
	}

	/**
	 * 属性approver的Setter方法.属性名：审批人 创建日期:
	 * 
	 * @param newApprover
	 *            java.lang.String
	 */
	public void setApprover(java.lang.String newApprover) {
		this.setAttributeValue("approver", newApprover);
	}

	/**
	 * 属性taudittime的Getter方法.属性名：审批日期 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getTaudittime() {
		return (nc.vo.pub.lang.UFDate) this.getAttributeValue("taudittime");
	}

	/**
	 * 属性taudittime的Setter方法.属性名：审批日期 创建日期:
	 * 
	 * @param newTaudittime
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setTaudittime(nc.vo.pub.lang.UFDate newTaudittime) {
		this.setAttributeValue("taudittime", newTaudittime);
	}

	/**
	 * 属性billmaker的Getter方法.属性名：制单人 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getBillmaker() {
		return (java.lang.String) this.getAttributeValue("billmaker");
	}

	/**
	 * 属性billmaker的Setter方法.属性名：制单人 创建日期:
	 * 
	 * @param newBillmaker
	 *            java.lang.String
	 */
	public void setBillmaker(java.lang.String newBillmaker) {
		this.setAttributeValue("billmaker", newBillmaker);
	}

	/**
	 * 属性tmaketime的Getter方法.属性名：制单日期 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getTmaketime() {
		return (nc.vo.pub.lang.UFDate) this.getAttributeValue("tmaketime");
	}

	/**
	 * 属性tmaketime的Setter方法.属性名：制单日期 创建日期:
	 * 
	 * @param newTmaketime
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setTmaketime(nc.vo.pub.lang.UFDate newTmaketime) {
		this.setAttributeValue("tmaketime", newTmaketime);
	}

	/**
	 * 属性fbillstatus的Getter方法.属性名：BOM状态 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getFbillstatus() {
		return (java.lang.Integer) this.getAttributeValue("fbillstatus");
	}

	/**
	 * 属性fbillstatus的Setter方法.属性名：BOM状态 创建日期:
	 * 
	 * @param newFbillstatus
	 *            java.lang.Integer
	 */
	public void setFbillstatus(java.lang.Integer newFbillstatus) {
		this.setAttributeValue("fbillstatus", newFbillstatus);
	}

	/**
	 * 属性hfbillstatus的Getter方法.属性名：父项BOM状态 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getHFbillstatus() {
		return (java.lang.Integer) this.getAttributeValue("hfbillstatus");
	}

	/**
	 * 属性fbillstatus的Setter方法.属性名：父项BOM状态 创建日期:
	 * 
	 * @param newFbillstatus
	 *            java.lang.Integer
	 */
	public void setHFbillstatus(java.lang.Integer newFbillstatus) {
		this.setAttributeValue("hfbillstatus", newFbillstatus);
	}

	/**
	 * 属性hvnote的Getter方法.属性名：备注 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvnote() {
		return (java.lang.String) this.getAttributeValue("hvnote");
	}

	/**
	 * 属性hvnote的Setter方法.属性名：备注 创建日期:
	 * 
	 * @param newHvnote
	 *            java.lang.String
	 */
	public void setHvnote(java.lang.String newHvnote) {
		this.setAttributeValue("hvnote", newHvnote);
	}

	/**
	 * 属性hcprojectid的Getter方法.属性名：项目 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHcprojectid() {
		return (java.lang.String) this.getAttributeValue("hcprojectid");
	}

	/**
	 * 属性hcprojectid的Setter方法.属性名：项目 创建日期:
	 * 
	 * @param newHcprojectid
	 *            java.lang.String
	 */
	public void setHcprojectid(java.lang.String newHcprojectid) {
		this.setAttributeValue("hcprojectid", newHcprojectid);
	}

	/**
	 * 属性hvchangerate的Getter方法.属性名：换算率 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvchangerate() {
		return (java.lang.String) this.getAttributeValue("hvchangerate");
	}

	/**
	 * 属性hvchangerate的Setter方法.属性名：换算率 创建日期:
	 * 
	 * @param newHvchangerate
	 *            java.lang.String
	 */
	public void setHvchangerate(java.lang.String newHvchangerate) {
		this.setAttributeValue("hvchangerate", newHvchangerate);
	}

	/**
	 * 属性hvdef1的Getter方法.属性名：自定义项1 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef1() {
		return (java.lang.String) this.getAttributeValue("hvdef1");
	}

	/**
	 * 属性hvdef1的Setter方法.属性名：自定义项1 创建日期:
	 * 
	 * @param newHvdef1
	 *            java.lang.String
	 */
	public void setHvdef1(java.lang.String newHvdef1) {
		this.setAttributeValue("hvdef1", newHvdef1);
	}

	/**
	 * 属性hvdef2的Getter方法.属性名：自定义项2 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef2() {
		return (java.lang.String) this.getAttributeValue("hvdef2");
	}

	/**
	 * 属性hvdef2的Setter方法.属性名：自定义项2 创建日期:
	 * 
	 * @param newHvdef2
	 *            java.lang.String
	 */
	public void setHvdef2(java.lang.String newHvdef2) {
		this.setAttributeValue("hvdef2", newHvdef2);
	}

	/**
	 * 属性hvdef3的Getter方法.属性名：自定义项3 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef3() {
		return (java.lang.String) this.getAttributeValue("hvdef3");
	}

	/**
	 * 属性hvdef3的Setter方法.属性名：自定义项3 创建日期:
	 * 
	 * @param newHvdef3
	 *            java.lang.String
	 */
	public void setHvdef3(java.lang.String newHvdef3) {
		this.setAttributeValue("hvdef3", newHvdef3);
	}

	/**
	 * 属性hvdef4的Getter方法.属性名：自定义项4 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef4() {
		return (java.lang.String) this.getAttributeValue("hvdef4");
	}

	/**
	 * 属性hvdef4的Setter方法.属性名：自定义项4 创建日期:
	 * 
	 * @param newHvdef4
	 *            java.lang.String
	 */
	public void setHvdef4(java.lang.String newHvdef4) {
		this.setAttributeValue("hvdef4", newHvdef4);
	}

	/**
	 * 属性hvdef5的Getter方法.属性名：自定义项5 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef5() {
		return (java.lang.String) this.getAttributeValue("hvdef5");
	}

	/**
	 * 属性hvdef5的Setter方法.属性名：自定义项5 创建日期:
	 * 
	 * @param newHvdef5
	 *            java.lang.String
	 */
	public void setHvdef5(java.lang.String newHvdef5) {
		this.setAttributeValue("hvdef5", newHvdef5);
	}

	/**
	 * 属性hvdef6的Getter方法.属性名：自定义项6 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef6() {
		return (java.lang.String) this.getAttributeValue("hvdef6");
	}

	/**
	 * 属性hvdef6的Setter方法.属性名：自定义项6 创建日期:
	 * 
	 * @param newHvdef6
	 *            java.lang.String
	 */
	public void setHvdef6(java.lang.String newHvdef6) {
		this.setAttributeValue("hvdef6", newHvdef6);
	}

	/**
	 * 属性hvdef7的Getter方法.属性名：自定义项7 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef7() {
		return (java.lang.String) this.getAttributeValue("hvdef7");
	}

	/**
	 * 属性hvdef7的Setter方法.属性名：自定义项7 创建日期:
	 * 
	 * @param newHvdef7
	 *            java.lang.String
	 */
	public void setHvdef7(java.lang.String newHvdef7) {
		this.setAttributeValue("hvdef7", newHvdef7);
	}

	/**
	 * 属性hvdef8的Getter方法.属性名：自定义项8 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef8() {
		return (java.lang.String) this.getAttributeValue("hvdef8");
	}

	/**
	 * 属性hvdef8的Setter方法.属性名：自定义项8 创建日期:
	 * 
	 * @param newHvdef8
	 *            java.lang.String
	 */
	public void setHvdef8(java.lang.String newHvdef8) {
		this.setAttributeValue("hvdef8", newHvdef8);
	}

	/**
	 * 属性hvdef9的Getter方法.属性名：自定义项9 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef9() {
		return (java.lang.String) this.getAttributeValue("hvdef9");
	}

	/**
	 * 属性hvdef9的Setter方法.属性名：自定义项9 创建日期:
	 * 
	 * @param newHvdef9
	 *            java.lang.String
	 */
	public void setHvdef9(java.lang.String newHvdef9) {
		this.setAttributeValue("hvdef9", newHvdef9);
	}

	/**
	 * 属性hvdef10的Getter方法.属性名：自定义项10 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef10() {
		return (java.lang.String) this.getAttributeValue("hvdef10");
	}

	/**
	 * 属性hvdef10的Setter方法.属性名：自定义项10 创建日期:
	 * 
	 * @param newHvdef10
	 *            java.lang.String
	 */
	public void setHvdef10(java.lang.String newHvdef10) {
		this.setAttributeValue("hvdef10", newHvdef10);
	}

	/**
	 * 属性hvdef11的Getter方法.属性名：自定义项11 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef11() {
		return (java.lang.String) this.getAttributeValue("hvdef11");
	}

	/**
	 * 属性hvdef11的Setter方法.属性名：自定义项11 创建日期:
	 * 
	 * @param newHvdef11
	 *            java.lang.String
	 */
	public void setHvdef11(java.lang.String newHvdef11) {
		this.setAttributeValue("hvdef11", newHvdef11);
	}

	/**
	 * 属性hvdef12的Getter方法.属性名：自定义项12 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef12() {
		return (java.lang.String) this.getAttributeValue("hvdef12");
	}

	/**
	 * 属性hvdef12的Setter方法.属性名：自定义项12 创建日期:
	 * 
	 * @param newHvdef12
	 *            java.lang.String
	 */
	public void setHvdef12(java.lang.String newHvdef12) {
		this.setAttributeValue("hvdef12", newHvdef12);
	}

	/**
	 * 属性hvdef13的Getter方法.属性名：自定义项13 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef13() {
		return (java.lang.String) this.getAttributeValue("hvdef13");
	}

	/**
	 * 属性hvdef13的Setter方法.属性名：自定义项13 创建日期:
	 * 
	 * @param newHvdef13
	 *            java.lang.String
	 */
	public void setHvdef13(java.lang.String newHvdef13) {
		this.setAttributeValue("hvdef13", newHvdef13);
	}

	/**
	 * 属性hvdef14的Getter方法.属性名：自定义项14 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef14() {
		return (java.lang.String) this.getAttributeValue("hvdef14");
	}

	/**
	 * 属性hvdef14的Setter方法.属性名：自定义项14 创建日期:
	 * 
	 * @param newHvdef14
	 *            java.lang.String
	 */
	public void setHvdef14(java.lang.String newHvdef14) {
		this.setAttributeValue("hvdef14", newHvdef14);
	}

	/**
	 * 属性hvdef15的Getter方法.属性名：自定义项15 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef15() {
		return (java.lang.String) this.getAttributeValue("hvdef15");
	}

	/**
	 * 属性hvdef15的Setter方法.属性名：自定义项15 创建日期:
	 * 
	 * @param newHvdef15
	 *            java.lang.String
	 */
	public void setHvdef15(java.lang.String newHvdef15) {
		this.setAttributeValue("hvdef15", newHvdef15);
	}

	/**
	 * 属性hvdef16的Getter方法.属性名：自定义项16 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef16() {
		return (java.lang.String) this.getAttributeValue("hvdef16");
	}

	/**
	 * 属性hvdef16的Setter方法.属性名：自定义项16 创建日期:
	 * 
	 * @param newHvdef16
	 *            java.lang.String
	 */
	public void setHvdef16(java.lang.String newHvdef16) {
		this.setAttributeValue("hvdef16", newHvdef16);
	}

	/**
	 * 属性hvdef17的Getter方法.属性名：自定义项17 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef17() {
		return (java.lang.String) this.getAttributeValue("hvdef17");
	}

	/**
	 * 属性hvdef17的Setter方法.属性名：自定义项17 创建日期:
	 * 
	 * @param newHvdef17
	 *            java.lang.String
	 */
	public void setHvdef17(java.lang.String newHvdef17) {
		this.setAttributeValue("hvdef17", newHvdef17);
	}

	/**
	 * 属性hvdef18的Getter方法.属性名：自定义项18 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef18() {
		return (java.lang.String) this.getAttributeValue("hvdef18");
	}

	/**
	 * 属性hvdef18的Setter方法.属性名：自定义项18 创建日期:
	 * 
	 * @param newHvdef18
	 *            java.lang.String
	 */
	public void setHvdef18(java.lang.String newHvdef18) {
		this.setAttributeValue("hvdef18", newHvdef18);
	}

	/**
	 * 属性hvdef19的Getter方法.属性名：自定义项19 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef19() {
		return (java.lang.String) this.getAttributeValue("hvdef19");
	}

	/**
	 * 属性hvdef19的Setter方法.属性名：自定义项19 创建日期:
	 * 
	 * @param newHvdef19
	 *            java.lang.String
	 */
	public void setHvdef19(java.lang.String newHvdef19) {
		this.setAttributeValue("hvdef19", newHvdef19);
	}

	/**
	 * 属性hvdef20的Getter方法.属性名：自定义项20 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvdef20() {
		return (java.lang.String) this.getAttributeValue("hvdef20");
	}

	/**
	 * 属性hvdef20的Setter方法.属性名：自定义项20 创建日期:
	 * 
	 * @param newHvdef20
	 *            java.lang.String
	 */
	public void setHvdef20(java.lang.String newHvdef20) {
		this.setAttributeValue("hvdef20", newHvdef20);
	}

	/**
	 * 属性hfbomsource的Getter方法.属性名：BOM来源 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getHfbomsource() {
		return (java.lang.Integer) this.getAttributeValue("hfbomsource");
	}

	/**
	 * 属性hfbomsource的Setter方法.属性名：BOM来源 创建日期:
	 * 
	 * @param newHfbomsource
	 *            java.lang.Integer
	 */
	public void setHfbomsource(java.lang.Integer newHfbomsource) {
		this.setAttributeValue("hfbomsource", newHfbomsource);
	}

	/**
	 * 属性hcecnid的Getter方法.属性名：ECN主键 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHcecnid() {
		return (java.lang.String) this.getAttributeValue("hcecnid");
	}

	/**
	 * 属性hcecnid的Setter方法.属性名：ECN主键 创建日期:
	 * 
	 * @param newHcecnid
	 *            java.lang.String
	 */
	public void setHcecnid(java.lang.String newHcecnid) {
		this.setAttributeValue("hcecnid", newHcecnid);
	}

	/**
	 * 属性hvecnbillcode的Getter方法.属性名：ECN号 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHvecnbillcode() {
		return (java.lang.String) this.getAttributeValue("hvecnbillcode");
	}

	/**
	 * 属性hvecnbillcode的Setter方法.属性名：ECN号 创建日期:
	 * 
	 * @param newHvecnbillcode
	 *            java.lang.String
	 */
	public void setHvecnbillcode(java.lang.String newHvecnbillcode) {
		this.setAttributeValue("hvecnbillcode", newHvecnbillcode);
	}

	/**
	 * 属性hrtversion的Getter方法.属性名：工艺路线版本 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHrtversion() {
		return (java.lang.String) this.getAttributeValue("hrtversion");
	}

	/**
	 * 属性hrtversion的Setter方法.属性名：工艺路线版本 创建日期:
	 * 
	 * @param newHrtversion
	 *            java.lang.String
	 */
	public void setHrtversion(java.lang.String newHrtversion) {
		this.setAttributeValue("hrtversion", newHrtversion);
	}

	/**
	 * 属性hiswholesetsend的Getter方法.属性名：成套发料 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getHiswholesetsend() {
		return (nc.vo.pub.lang.UFBoolean) this
				.getAttributeValue("hiswholesetsend");
	}

	/**
	 * 属性hiswholesetsend的Setter方法.属性名：成套发料 创建日期:
	 * 
	 * @param newHiswholesetsend
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setHiswholesetsend(nc.vo.pub.lang.UFBoolean newHiswholesetsend) {
		this.setAttributeValue("hiswholesetsend", newHiswholesetsend);
	}

	/**
	 * 属性hisvirtual的Getter方法.属性名：虚项 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getHisvirtual() {
		return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("hisvirtual");
	}

	/**
	 * 属性hisvirtual的Setter方法.属性名：虚项 创建日期:
	 * 
	 * @param newHisvirtual
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setHisvirtual(nc.vo.pub.lang.UFBoolean newHisvirtual) {
		this.setAttributeValue("hisvirtual", newHisvirtual);
	}

	/**
	 * 属性bkititem的Getter方法.属性名：齐套 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getBkititem() {
		return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("bkititem");
	}

	/**
	 * 属性bkititem的Setter方法.属性名：齐套 创建日期:
	 * 
	 * @param newBkititem
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setBkititem(nc.vo.pub.lang.UFBoolean newBkititem) {
		this.setAttributeValue("bkititem", newBkititem);
	}

	/**
	 * 属性hmaterialvid的Getter方法.属性名：物料最新版本 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHmaterialvid() {
		return (java.lang.String) this.getAttributeValue("hmaterialvid");
	}

	/**
	 * 属性hmaterialvid的Setter方法.属性名：物料最新版本 创建日期:
	 * 
	 * @param newHmaterialvid
	 *            java.lang.String
	 */
	public void setHmaterialvid(java.lang.String newHmaterialvid) {
		this.setAttributeValue("hmaterialvid", newHmaterialvid);
	}

	/**
	 * 属性hcmaterialname的Getter方法.属性名：物料名称 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHcmaterialname() {
		return (java.lang.String) this.getAttributeValue("hcmaterialname");
	}

	/**
	 * 属性hcmaterialname的Setter方法.属性名：物料名称 创建日期:
	 * 
	 * @param newHcmaterialname
	 *            java.lang.String
	 */
	public void setHcmaterialname(java.lang.String newHcmaterialname) {
		this.setAttributeValue("hcmaterialname", newHcmaterialname);
	}

	/**
	 * 属性hlevelno的Getter方法.属性名：层码 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHlevelno() {
		return (java.lang.String) this.getAttributeValue("hlevelno");
	}

	/**
	 * 属性hlevelno的Setter方法.属性名：层码 创建日期:
	 * 
	 * @param newHlevelno
	 *            java.lang.String
	 */
	public void setHlevelno(java.lang.String newHlevelno) {
		this.setAttributeValue("hlevelno", newHlevelno);
	}

	/**
	 * 属性hfmaterialid的Getter方法.属性名：父项物料编码 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHfmaterialid() {
		return (java.lang.String) this.getAttributeValue("hfmaterialid");
	}

	/**
	 * 属性hfmaterialid的Setter方法.属性名：父项物料编码 创建日期:
	 * 
	 * @param newHfmaterialid
	 *            java.lang.String
	 */
	public void setHfmaterialid(java.lang.String newHfmaterialid) {
		this.setAttributeValue("hfmaterialid", newHfmaterialid);
	}

	/**
	 * 属性hfbomtype的Getter方法.属性名：父项BOM类型 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getHfbomtype() {
		return (java.lang.Integer) this.getAttributeValue("hfbomtype");
	}

	/**
	 * 属性hfbomtype的Setter方法.属性名：父项BOM类型 创建日期:
	 * 
	 * @param newHfbomtype
	 *            java.lang.Integer
	 */
	public void setHfbomtype(java.lang.Integer newHfbomtype) {
		this.setAttributeValue("hfbomtype", newHfbomtype);
	}

	/**
	 * 属性hfbomversion的Getter方法.属性名：父项BOM版本 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHfbomversion() {
		return (java.lang.String) this.getAttributeValue("hfbomversion");
	}

	/**
	 * 属性hfbomversion的Setter方法.属性名：父项BOM版本 创建日期:
	 * 
	 * @param newHfbomversion
	 *            java.lang.String
	 */
	public void setHfbomversion(java.lang.String newHfbomversion) {
		this.setAttributeValue("hfbomversion", newHfbomversion);
	}

	/**
	 * 属性hsrcid的Getter方法.属性名：源BOMID 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getHsrcid() {
		return (java.lang.String) this.getAttributeValue("hsrcid");
	}

	/**
	 * 属性hsrcid的Setter方法.属性名：源BOMID 创建日期:
	 * 
	 * @param newHsrcid
	 *            java.lang.String
	 */
	public void setHsrcid(java.lang.String newHsrcid) {
		this.setAttributeValue("hsrcid", newHsrcid);
	}

	/**
	 * 属性vbillcode的Getter方法.属性名：单据号 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getVbillcode() {
		return (java.lang.String) this.getAttributeValue("vbillcode");
	}

	/**
	 * 属性vbillcode的Setter方法.属性名：单据号 创建日期:
	 * 
	 * @param newVbillcode
	 *            java.lang.String
	 */
	public void setVbillcode(java.lang.String newVbillcode) {
		this.setAttributeValue("vbillcode", newVbillcode);
	}

	/**
	 * 属性vbilltype的Getter方法.属性名：单据类型 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getVbilltype() {
		return (java.lang.String) this.getAttributeValue("vbilltype");
	}

	/**
	 * 属性vbilltype的Setter方法.属性名：单据类型 创建日期:
	 * 
	 * @param newVbilltype
	 *            java.lang.String
	 */
	public void setVbilltype(java.lang.String newVbilltype) {
		this.setAttributeValue("vbilltype", newVbilltype);
	}

	/**
	 * 属性hbcustomized的Getter方法.属性名：是否定制 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getHbcustomized() {
		return (nc.vo.pub.lang.UFBoolean) this
				.getAttributeValue("hbcustomized");
	}

	/**
	 * 属性hbcustomized的Setter方法.属性名：是否定制 创建日期:
	 * 
	 * @param newHbcustomized
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setHbcustomized(nc.vo.pub.lang.UFBoolean newHbcustomized) {
		this.setAttributeValue("hbcustomized", newHbcustomized);
	}

	/**
	 * 属性dr的Getter方法.属性名：dr 创建日期:
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr() {
		return (java.lang.Integer) this.getAttributeValue("dr");
	}

	/**
	 * 属性dr的Setter方法.属性名：dr 创建日期:
	 * 
	 * @param newDr
	 *            java.lang.Integer
	 */
	public void setDr(java.lang.Integer newDr) {
		this.setAttributeValue("dr", newDr);
	}

	/**
	 * 属性ts的Getter方法.属性名：ts 创建日期:
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs() {
		return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("ts");
	}

	/**
	 * 属性ts的Setter方法.属性名：ts 创建日期:
	 * 
	 * @param newTs
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
		this.setAttributeValue("ts", newTs);
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getPKFieldName() {
		return "cbomid";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getTableName() {
		return "bd_bom";
	}

	/**
	 * 按照默认方式创建构造子. 创建日期:
	 */
	public BomVO() {
		super();
	}

	@Override
	@nc.vo.annotation.MDEntityInfo(beanFullclassName = "nc.vo.bd.bom.bom0202.entity.BomVO")
	public IVOMeta getMetaData() {
		IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("mmbd.bd_bom");
		return meta;
	}
}
