/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.cm.fetchdata.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFDate;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class PullDataStateVO extends SuperVO {
	
	
	private java.lang.String pk_workitem;
	private java.lang.String pk_costobject;
	private java.lang.String pk_qcdept;
	private java.lang.String pk_serverdept;
	private java.lang.String pk_largeritem;
	private java.lang.String pk_factor;
	private java.lang.String pk_factorgroup;

    /**
     * 预留：按财务组织取数使用
     */
    private String[] pk_orgs;

    private java.lang.String cfetchinfoid;

    private java.lang.String pk_group;

    private java.lang.String pk_org;

    private java.lang.String pk_org_v;

    private java.lang.String cperiod;

    private nc.vo.pub.lang.UFDate dbegindate;

    private nc.vo.pub.lang.UFDate denddate;

    private nc.vo.pub.lang.UFBoolean bfetched;

    // 取数方案1按月2按周期
    private java.lang.Integer ifetchscheme = 1;

    // 取数对象： 1 材料出，2产成品入 3 废品 4 作业
    private java.lang.Integer ifetchobjtype = 1;

    private java.lang.String ccostcenterid;

    private java.lang.Integer nday;

    // 取数类型：1存货核算，2生产制造 4废品取数
    private java.lang.Integer pulldatatype = 1;

    private java.lang.Integer cbilltype;

    private java.lang.String ctranstypeid;

    // 交易类型数组
    private java.lang.String[] ctranstypeids;

    // 成本中心数组
    private java.lang.String[] costcenterids;

    private java.lang.Integer dr = 0;

    private nc.vo.pub.lang.UFDateTime ts;

    // 业务日期
    private UFDate busiDate = null;

    public static final String CFETCHINFOID = "cfetchinfoid";

    public static final String PK_GROUP = "pk_group";

    public static final String PK_ORG = "pk_org";

    public static final String PK_ORG_V = "pk_org_v";

    public static final String CPERIOD = "cperiod";

    public static final String DBEGINDATE = "dbegindate";

    public static final String DENDDATE = "denddate";

    public static final String BFETCHED = "bfetched";

    public static final String IFETCHSCHEME = "ifetchscheme";

    public static final String IFETCHOBJTYPE = "ifetchobjtype";

    public static final String CCOSTCENTERID = "ccostcenterid";

    public static final String NDAY = "nday";

    public static final String PULLDATATYPE = "pulldatatype";

    public static final String CBILLTYPE = "cbilltype";

    public static final String CTRANSTYPEID = "ctranstypeid";

    /**
     * 属性cfetchinfoid的Getter方法.
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCfetchinfoid() {
        return this.cfetchinfoid;
    }

    /**
     * 属性cfetchinfoid的Setter方法.
     * 创建日期:
     * 
     * @param newCfetchinfoid java.lang.String
     */
    public void setCfetchinfoid(java.lang.String newCfetchinfoid) {
        this.cfetchinfoid = newCfetchinfoid;
    }

    /**
     * 属性pk_group的Getter方法.
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_group() {
        return this.pk_group;
    }

    /**
     * 属性pk_group的Setter方法.
     * 创建日期:
     * 
     * @param newPk_group java.lang.String
     */
    public void setPk_group(java.lang.String newPk_group) {
        this.pk_group = newPk_group;
    }

    /**
     * 属性pk_org的Getter方法.
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org() {
        return this.pk_org;
    }

    /**
     * 属性pk_org的Setter方法.
     * 创建日期:
     * 
     * @param newPk_org java.lang.String
     */
    public void setPk_org(java.lang.String newPk_org) {
        this.pk_org = newPk_org;
    }

    /**
     * 属性pk_org_v的Getter方法.
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org_v() {
        return this.pk_org_v;
    }

    /**
     * 属性pk_org_v的Setter方法.
     * 创建日期:
     * 
     * @param newPk_org_v java.lang.String
     */
    public void setPk_org_v(java.lang.String newPk_org_v) {
        this.pk_org_v = newPk_org_v;
    }

    /**
     * 属性cperiod的Getter方法.
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCperiod() {
        return this.cperiod;
    }

    /**
     * 属性cperiod的Setter方法.
     * 创建日期:
     * 
     * @param newCperiod java.lang.String
     */
    public void setCperiod(java.lang.String newCperiod) {
        this.cperiod = newCperiod;
    }

    /**
     * 属性dbegindate的Getter方法.
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDate
     */
    public nc.vo.pub.lang.UFDate getDbegindate() {
        return this.dbegindate;
    }

    /**
     * 属性dbegindate的Setter方法.
     * 创建日期:
     * 
     * @param newDbegindate nc.vo.pub.lang.UFDate
     */
    public void setDbegindate(nc.vo.pub.lang.UFDate newDbegindate) {
        this.dbegindate = newDbegindate;
    }

    /**
     * 属性denddate的Getter方法.
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDate
     */
    public nc.vo.pub.lang.UFDate getDenddate() {
        return this.denddate;
    }

    /**
     * 属性denddate的Setter方法.
     * 创建日期:
     * 
     * @param newDenddate nc.vo.pub.lang.UFDate
     */
    public void setDenddate(nc.vo.pub.lang.UFDate newDenddate) {
        this.denddate = newDenddate;
    }

    /**
     * 属性bfetched的Getter方法.
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getBfetched() {
        return this.bfetched;
    }

    /**
     * 属性bfetched的Setter方法.
     * 创建日期:
     * 
     * @param newBfetched nc.vo.pub.lang.UFBoolean
     */
    public void setBfetched(nc.vo.pub.lang.UFBoolean newBfetched) {
        this.bfetched = newBfetched;
    }

    /**
     * 属性ifetchscheme的Getter方法.
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getIfetchscheme() {
        return this.ifetchscheme;
    }

    /**
     * 属性ifetchscheme的Setter方法.
     * 创建日期:
     * 
     * @param newIfetchscheme java.lang.Integer
     */
    public void setIfetchscheme(java.lang.Integer newIfetchscheme) {
        this.ifetchscheme = newIfetchscheme;
    }

    /**
     * 属性ifetchobjtype的Getter方法.
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getIfetchobjtype() {
        return this.ifetchobjtype;
    }

    /**
     * 属性ifetchobjtype的Setter方法.
     * 创建日期:
     * 
     * @param newIfetchobjtype java.lang.Integer
     */
    public void setIfetchobjtype(java.lang.Integer newIfetchobjtype) {
        this.ifetchobjtype = newIfetchobjtype;
    }

    /**
     * 属性ccostcenterid的Getter方法.
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCcostcenterid() {
        return this.ccostcenterid;
    }

    /**
     * 属性ccostcenterid的Setter方法.
     * 创建日期:
     * 
     * @param newCcostcenterid java.lang.String
     */
    public void setCcostcenterid(java.lang.String newCcostcenterid) {
        this.ccostcenterid = newCcostcenterid;
    }

    /**
     * 属性nday的Getter方法.
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getNday() {
        return this.nday;
    }

    /**
     * 属性nday的Setter方法.
     * 创建日期:
     * 
     * @param newNday java.lang.Integer
     */
    public void setNday(java.lang.Integer newNday) {
        this.nday = newNday;
    }

    /**
     * 属性pulldatatype的Getter方法.
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getPulldatatype() {
        return this.pulldatatype;
    }

    /**
     * 属性pulldatatype的Setter方法.
     * 创建日期:
     * 
     * @param newPulldatatype java.lang.Integer
     */
    public void setPulldatatype(java.lang.Integer newPulldatatype) {
        this.pulldatatype = newPulldatatype;
    }

    /**
     * 属性cbilltype的Getter方法.
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.Integer getCbilltype() {
        return this.cbilltype;
    }

    /**
     * 属性cbilltype的Setter方法.
     * 创建日期:
     * 
     * @param newCbilltype java.lang.String
     */
    public void setCbilltype(java.lang.Integer newCbilltype) {
        this.cbilltype = newCbilltype;
    }

    /**
     * 属性ctranstypeid的Getter方法.
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCtranstypeid() {
        return this.ctranstypeid;
    }

    /**
     * 属性ctranstypeid的Setter方法.
     * 创建日期:
     * 
     * @param newCtranstypeid java.lang.String
     */
    public void setCtranstypeid(java.lang.String newCtranstypeid) {
        this.ctranstypeid = newCtranstypeid;
    }

    /**
     * 属性dr的Getter方法.
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getDr() {
        return this.dr;
    }

    /**
     * 属性dr的Setter方法.
     * 创建日期:
     * 
     * @param newDr java.lang.Integer
     */
    public void setDr(java.lang.Integer newDr) {
        this.dr = newDr;
    }

    /**
     * 属性ts的Getter方法.
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getTs() {
        return this.ts;
    }

    /**
     * 属性ts的Setter方法.
     * 创建日期:
     * 
     * @param newTs nc.vo.pub.lang.UFDateTime
     */
    public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
        this.ts = newTs;
    }

    /**
     * <p>
     * 取得父VO主键字段.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getParentPKFieldName() {
        return null;
    }

    /**
     * <p>
     * 取得表主键.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getPKFieldName() {
        return "cfetchinfoid";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getTableName() {
        return "cm_fetchinfo";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public static java.lang.String getDefaultTableName() {
        return "cm_fetchinfo";
    }

    @Override
    public IVOMeta getMetaData() {
        return VOMetaFactory.getInstance().getVOMeta("cm.cm_fetchinfo");

    }

    /**
     * 按照默认方式创建构造子.
     * 创建日期:
     */
    public PullDataStateVO() {
        super();
    }

    public java.lang.String[] getCtranstypeids() {
        return this.ctranstypeids;
    }

    public void setCtranstypeids(java.lang.String[] ctranstypeids) {
        this.ctranstypeids = ctranstypeids;
    }

    public UFDate getBusiDate() {
        return this.busiDate;
    }

    public void setBusiDate(UFDate busiDate) {
        this.busiDate = busiDate;
    }

    public String[] getPk_orgs() {
        return this.pk_orgs;
    }

    public void setPk_orgs(String[] pk_orgs) {
        this.pk_orgs = pk_orgs;
    }

    /**
     * 获得 costcenterids 的属性值
     * 
     * @return the costcenterids
     * @since 2015-1-23
     * @author zhangweix
     */
    public java.lang.String[] getCostcenterids() {
        return this.costcenterids;
    }

    /**
     * 设置 costcenterids 的属性值
     * 
     * @param costcenterids the costcenterids to set
     * @since 2015-1-23
     * @author zhangweix
     */
    public void setCostcenterids(java.lang.String[] costcenterids) {
        this.costcenterids = costcenterids;
    }

	public java.lang.String getPk_workitem() {
		return pk_workitem;
	}

	public void setPk_workitem(java.lang.String pk_workitem) {
		this.pk_workitem = pk_workitem;
	}

	public java.lang.String getPk_costobject() {
		return pk_costobject;
	}

	public void setPk_costobject(java.lang.String pk_costobject) {
		this.pk_costobject = pk_costobject;
	}

	public java.lang.String getPk_qcdept() {
		return pk_qcdept;
	}

	public void setPk_qcdept(java.lang.String pk_qcdept) {
		this.pk_qcdept = pk_qcdept;
	}

	public java.lang.String getPk_serverdept() {
		return pk_serverdept;
	}

	public void setPk_serverdept(java.lang.String pk_serverdept) {
		this.pk_serverdept = pk_serverdept;
	}

	public java.lang.String getPk_largeritem() {
		return pk_largeritem;
	}

	public void setPk_largeritem(java.lang.String pk_largeritem) {
		this.pk_largeritem = pk_largeritem;
	}

	public java.lang.String getPk_factor() {
		return pk_factor;
	}

	public void setPk_factor(java.lang.String pk_factor) {
		this.pk_factor = pk_factor;
	}

	public java.lang.String getPk_factorgroup() {
		return pk_factorgroup;
	}

	public void setPk_factorgroup(java.lang.String pk_factorgroup) {
		this.pk_factorgroup = pk_factorgroup;
	}
    
    
}
